services:
  website-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: website_test
    env_file:
      - .env
    ports:
      # Maps local port 8000 on your VPS to port 3000 inside the Express container
      - "127.0.0.1:8000:3000"
    restart: always
    volumes:
      # Persists assets across updates
      - ./assets:/app/assets
