server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;

        # Crucial directive for Single Page Apps (SPA)
        # It attempts to serve the request as a file, then directory,
        # and falls back to loading index.html so React's internal router works.
        try_files $uri $uri/ /index.html;
    }

    # Custom Error Handling pages
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }

    # Enable aggressive cache handles for performance
    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|svg|woff|woff2|mp4)$ {
        root /usr/share/nginx/html;
        expires 1y;
        access_log off;
        add_header Cache-Control "public, no-transform";
    }
}
